config/routes.rb
WineReview::Application.routes.draw do
  resources :wines do
    resources :logentries
    get 'page/:page', :action => :index, :on => :collection
  end
  root 'wines#index'

end

app/models/logentry.rb
class Logentry < ActiveRecord::Base
  belongs_to :wine
  STARS = 1..5
  validates :name, :rating, :location, :comments, :tasted_on, presence: true
  validates :comments, length: { minimum: 3 }, unless: 'comments.blank?'
  validates :rating, inclusion: { in: STARS, message: "must be from #{STARS.first} to #{STARS.last}" }
end

app/models/wine.rb
class Wine < ActiveRecord::Base
	def average_ratings
      logentries.average(:rating)
    end
	has_many :logentries, dependent: :destroy
	validates :name, :year, :country, presence: true
validates :year,
   numericality: { only_integer: true, greater_than_or_equal_to: 0 },
   unless: "year.blank?"
   	validates :varietal, inclusion: { in: %w(MERLOT CHIANTI CABERNET),
    message: "%{value} is not a valid type, must be MERLOT CHIANTI CABERNET" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout ->(controller) { controller.request.xhr? ? false : 'application' }
end

app/controllers/logentries_controller.rb
class LogentriesController < ApplicationController
	before_action :set_wine

  def index
    @logentries = @wine.logentries.order('created_at desc')
  end

  def new
    @logentry = @wine.logentries.new
  end

  def create
    @logentry = @wine.logentries.new(logentry_params)
    if @logentry.save
      redirect_to wine_logentries_path(@wine), notice: 'logentry saved!'
    else
      render :new
    end
  end

  private

  def set_wine
    @wine = Wine.find(params[:wine_id])
  end

  def logentry_params
    params.require(:logentry).permit(:name, :rating, :location, :comments, :tasted_on)
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: [ :show, :edit, :update, :destroy ]
  def index
    @available_at = Time.now
    @wines = Wine.order(:name).page(params[:page])
  end
  def show
  end
  def new
    @wine = Wine.new
  end
  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to @wine, notice: "#{@wine.name} was created!"
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @wine.update(wine_params)
      redirect_to @wine, notice: "#{@wine.name} was updated!"
    else
      render :new
    end
  end
  def destroy
    @wine.destroy
    redirect_to wines_url
  end
private
  def wine_params
    params.require(:wine).permit(:name, :year, :winery, :country, :varietal)
  end
  def set_wine
    @wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logentries_helper.rb
module LogentriesHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <h3 class="text-center text-muted">For Educational Uses Only</h3>
  </div>
</nav>

app/views/layouts/_header.html.erb
<header class="page-header">
<h1><%= link_to('Yum Wines', root_path) %></h1>
</header>

app/views/layouts/_sidebar.html.erb
<div id="sidebar">
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Navigation</h3>
  </div>
  <div class="panel-body">
    <p>
      <%= link_to 'All Wines', wines_path %>
    </p>
    <p>
      <%= link_to 'Create Wine', new_wine_path %>
    </p>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yum Wines <%= yield :name %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render '/layouts/header' %>
  </div>
  <div class="container">
    <div class="col-xs-9">
      <%= render '/shared/flashes' %>
      <%= yield %>
    </div>
    <div class="col-xs-3">
      <%= render '/layouts/sidebar' %>
    </div>
  </div>
  <%= render '/layouts/footer' %>
</body>
</html>

app/views/logentries/_form.html.erb
<%= form_for( [ @wine, @logentry ] ) do |f| %>
  <%= render 'shared/validation_errors', object: @logentry %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, placeholder: 'Name' %><br />
  <%= f.label :rating %>  
  <% Logentry::STARS.each do |star| %>
    <%= f.radio_button :rating, star %> <%= star %>
  <% end %><br />
  <%= f.label :location %>
  <%= f.text_field :location %><br/>
  <%= f.label :comments %><br/>
  <%= f.text_area :comments %><br/>
  <%= f.label :tasted_on %>
  <%= f.date_select :tasted_on %><br/>
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wine_logentries_path(@wine), id: 'cancel_logentry' %>
  </p>
  
<% end %>

app/views/logentries/index.html.erb
<header>Reviews for <%= link_to(@wine.name, @wine) %></header>
<ol id="reviews">
  <% @logentries.each do |review| %>
    <li>
      <span class="review"><%= pluralize(review.rating, 'rating') %></span>
      <span class="user">by <%= review.name %> </span>
      <span class="date">
        <%= time_ago_in_words(review.created_at) %> ago
      </span>
      <p>
        &quot;<%= review.comments %>&quot;
      </p>
    </li>
  <% end %>
</ol>
<%= link_to 'Write a Review', new_wine_logentry_path(@wine),
        remote: true,
        data: { 'update-target' => 'logentry_form_container' },
        class: 'btn btn-primary' %>

<div id="logentry_form_container"></div>

app/views/logentries/new.html.erb
<h1>Write a review for <%= @wine.name %></h1>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if flash.present? %>
  <div id="flashes">
    <% flash.each do |key, value| %>
      <p class="flash <%= key %>"><%= value %></p>
    <% end %>
  </div>
<% end %>

app/views/shared/_validation_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    Oops! The <%= object.class.name.humanize.downcase %> could not be saved.<br />
    Correct the following <%= pluralize(object.errors.count, "error") %>:
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/wines/_form.html.erb
<%= form_for(@wine) do |f| %>
<%= render 'shared/validation_errors', object: @wine %>
  <%= f.label :name %> <%= f.text_field :name, autofocus: true %><br />
  <%= f.label :year %> <%= f.text_field :year %><br />
  <%= f.label :winery %> <%= f.text_field :winery %><br />
  <%= f.label :country %> <%= f.text_field :country %><br />
  <%= f.label :varietal %> <%= f.select(:varietal, ['MERLOT', 'CHIANTI', 'CABERNET']) %><br />
  <p>
    <%= f.submit %>
    <%= link_to 'Cancel', wines_path %>
  </p>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine <%= @wine.name %></h1>
<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines</h1>
<p>Available as of <%= @available_at %></p>
<%= page_entries_info @wines %>
<ol>
<% @wines.each do |wine| %>
  <li>Name: <%= link_to(wine.name, wine) %>
      Winery: <%= wine.winery %>
      Varietal: <%= wine.varietal %></li>
<% end %>
</ol>
<%= paginate @wines %>

app/views/wines/new.html.erb
<h1>Create a New Wine</h1>
<%= render 'form' %>

app/views/wines/show.html.erb
<% content_for :name, @wine.name %>
<article class="wine">
  <header>
    <h2><%= @wine.name %></h2>
  </header>
  <p><label>Year:</label> <%= @wine.year %></p>
  <p><label>Winery:</label> <%= @wine.winery %></p>
  <p><label>Country:</label> <%= @wine.country %></p>
  <p><label>Varietal:</label> <%= @wine.varietal %></p>
  <p>
  Read all
  <%= link_to pluralize(@wine.logentries.size, 'logentry'), 
                        wine_logentries_path(@wine) %>
</p>
<p><label>Average Review:</label> <%= @wine.average_ratings %></p>
</article>

<%= link_to 'All Wines', wines_path %>
| <%= link_to 'Edit', edit_wine_path(@wine) %>
<%= button_to 'Delete', @wine,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>